# -*- coding: utf-8 -*-
"""Capitulo2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12n_IrPf0v6v9os6LWPjCGbrtzWnNFBs-
"""

#True or false  
nome = input("Digite o seu nome: ")

if len(nome) > 20:
  print("O nome deve ter no máximo 20 caracteres!")
  nome = input("Digite o seu nome: ")
  
print("Nome digitado: {}".format(nome))

usuario = input("Digite o seu usuário: ")
senha = input("Digite a sua senha: ")

if (usuario == "Vinicius") and (senha == "Secret"):
  print("Welcome, {}".format(usuario))
else:
  print("Usuário ou senha inválidos")

#tem carteira de moto
#tem carteira de carro
#Se tiver carteira de carro, nível 1 
#Se tiver carteira de moto, nível 2 
#Se tiver carteira de carro e moto, nível 3
#Algoritmo para calcular o nivel do funcionário

questao = input("Você tem carteira de moto (S/N)?")
carteira_moto = (questao.upper() == "S") or (questao.upper() == "SIM")
questao = input("Você tem carteira de carro (S/N)?")
carteira_carro = (questao.upper() == "S") or (questao.upper() == "SIM")

if(not(carteira_moto)) and (carteira_carro):
  print("Você está no nível 1")
elif(carteira_moto) and (not(carteira_carro)):
    print("Você está no nível 2")
elif(carteira_moto) and (carteira_carro):
      print("Você está no nível 3")

#primeiro_emprego?
#tem alguma carteira
#Quero saber se ele tem vaga ou não na empresa
#Ele tem vaga se é o primeiro emprego OU ele já tem alguma habilitação

questao = input("Esse é o seu primeiro emprego (S/N)?")
primeiro_emprego = (questao.upper() == "S") or (questao.upper() == "SIM")
questao = input("Você tem habilitação (S/N)?")
habilitacao = (questao.upper() == "S") or (questao.upper() == "SIM")

if (primeiro_emprego) or (habilitacao):
  print("Você pode trabalhar na nossa empressa")
else:
  print("Descupla, não há vagas para você")

#Jogo de dados
#Escolher entre 1 e 6
#Escolho quanto apostar (Máximo 100)
#Jogo 2 dados
#Se 1 dado igual ganho 2 vezes o valor apostado
#Se 2 dados derem iguais 10 vezes o valor apostado
#Se não der nenhum dado igual perco meu dinheiro

from random import randrange

bolso = 100
numero_apostado = int(input("Qual número você aposta? "))
valor_aposta = float(input("Qual o valor da aposta? "))
if valor_aposta > bolso:
  print("Você não tem dinheiro")
else:
  bolso -= valor_aposta
  #gera num aleatório dentro de um range- necessário importar randrange
  dado1 = randrange(1,6)
  dado2 = randrange(1,6)

  mensagem_ganhou = "Você ganhou {} e agora esta com {}"

  print("Números sorteados: {} e {} ".format(dado1,dado2))
  resultado = 0

  if (dado1 == numero_apostado) and (dado2 == numero_apostado):
    resultado = valor_aposta*10
    bolso += resultado
    print(mensagem_ganhou.format(resultado,bolso))

  elif (dado1 == numero_apostado) or (dado2 == numero_apostado):
    resultado = valor_aposta*2
    bolso += resultado
    print(mensagem_ganhou.format(resultado,bolso))
    
  else:
    print("Você errou, agora esta com {}".format(bolso))

#Cálculo do IMC
#Equação IMC = peso / (altura ** 2)
#abaixo 17 => muito abaixo do peso
#entre 17 e 18.5 => abaixo do peso
#entre 18.5 e 25 => peso normal
#entre 25 e 30 => acima do peso
#entre 30 e 35 => obesidade grau I
#entre 35 e 40 => obesidade grau II
#acima de 40 => obesidade mórbida

print("Olá, vamos ajudar você a ficar saudável. \nPrimeiro precisamos calcular seu IMC")
peso = float(input("Digite seu peso: "))
altura = float(input("Digite sua altura: "))
imc = peso / (altura**2)

print("Seu IMC é {}".format(imc))

if (imc < 17):
  print("Você esta muito abaixo do peso")

elif (imc >= 17) and (imc < 18.5):
  print("Você esta abaixo do peso")

elif (imc >= 18.5) and (imc < 25):
  print("Você esta no peso normal")

elif (imc >= 25) and (imc < 30):
  print("Você esta acima do peso")

elif (imc >= 30) and (imc < 35):
  print("Você esta com obesidade I")

elif (imc >= 35) and (imc < 40):
  print("Você esta com obesidade II")

elif (imc >= 40):
  print("Você esta com mórbida")