# -*- coding: utf-8 -*-
"""Capítulo3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/198GNxOeWSdwYRPyyp5caTTe6Y6aBM-0O
"""

pessoa = {
    "nome" : "Vinicius",
    "endereco": "Rua X",
    "idade": 24
}

print(pessoa)
print(pessoa['idade'])

lista=['Vinicius', 'Marcos', 'Vanessa', 'Claudia']
print(lista)
print(lista[0])
print(lista[-1])
print(lista[:3])
lista[0] = 'Henrique'
print(lista)
print("O tamanho da lista é {}".format(len(lista)))

nome = 'Vinicius'
print(nome[0])

lista=['Vinicius', 'Marcos', 'Vanessa', 'Claudia']
print(lista)
lista.append('Pedro')

lista_copia = lista.copy()
lista_copia[0] = 'Henrique'
print(lista)
print(lista_copia)

lista=['Vinicius', 'Marcos', 'Vanessa', 'Claudia']
lista.insert(2,'Pedro')
print(lista)
lista.remove('Pedro')
print(lista)

lista=['Vinicius', 'Marcos', 'Vanessa', 'Claudia']
nome_retirado = lista.pop(0)
print(lista)
print(nome_retirado)

lista = ['Vinicius', 'Marcos', 'Pedro', 'Vanessa', 'Claudia']

if('Pedro' in lista):
  print('O Pedro está na lista')

tupla = ('Vinicius', 'Marcos', 'Pedro', 'Vanessa', 'Claudia')
print(tupla)
print('Vinicius' in tupla)

lista_pessoas = []
lista_pessoas.append({
    "nome":"Vinicius",
    "endereco": "Rua X",
    "idade" : 24
})
lista_pessoas.append({
    "nome":"Vanessa",
    "endereco": "Rua Y",
    "idade" : 26
})
lista_pessoas.append({
    "nome":"Claudia",
    "endereco": "Rua Z",
    "idade" : 36
})
print(lista_pessoas)

senha_correta = False
tentativas = 3;

while (not senha_correta) and (tentativas > 0):
  senha = input("Digite a sua senha: ")
  senha_correta = senha == 'secreto'
  if(not senha_correta):
    print("A senha não está correta")
    senha_correta = True
    tentativas -= 1

if senha_correta:
  print("Parabéns, você acertou a senha")
else:
  print("Acesso bloqueado")

lista_pessoas = []
lista_pessoas.append({
    "id": 1,
    "nome":"Vinicius",
    "endereco": "Rua X",
    "idade" : 24,
    "salario" : 1000.00
})
lista_pessoas.append({
    "id": 2,
    "nome":"Vanessa",
    "endereco": "Rua Y",
    "idade" : 26,
    "salario" : 5000.00
})
lista_pessoas.append({
    "id": 3,
    "nome":"Claudia",
    "endereco": "Rua Z",
    "idade" : 36,
    "salario" : 10000.90
})

for pessoa in lista_pessoas:
  print("A pessoa de id {} tem o nome de {}".format(pessoa["id"],pessoa["nome"]))

print("\n\nMostrando pessoas com salário maior que R$1000,00")
for pessoa in lista_pessoas:
  if(pessoa["salario"]>1000):
    print("A pessoa de id {} tem o nome de {} e ganha {}".format(pessoa["id"],pessoa["nome"],pessoa["salario"]))

#mostra os números de 1 a 10
#usando range - intervalo de números
for numero in range(1,11):
  print("Número {}".format(numero))

#mostra os números de 1 a 10, que são pares
#usando range - intervalo de números, pulando de 2 em 2
for numero in range(2,11):
  print("Número {}".format(numero))

from getpass import getpass, getuser

#getpass - "esconde a senha"
senha = getpass("Digite a sua senha: ")

#getuser - retorna o usuario que esta usando o sistema
usuario = getuser()
print(usuario)

#Digitar item da compra e quantidade
#Verificar o valor total
#Quando encerrar, dar valor total da compra

produtos = ['Hambuguer', 'Batata fritas', 'Combo', 'Refrigerante']
precos = [15, 10.5, 20, 5]
itens_comprados = []

valor_total = 0
item_compra = int(input("Qual o identificador do item da compra? "))
itens_comprados.append(produtos[item_compra])

informacao = input("Qual a quantidade consumida? ")
while (not informacao.isdigit()):
  informacao = input("A quantidade consumida deve ser em um número. \nDigite novamente: ")
quantidade = int(informacao)

while item_compra != -1:
  valor_total += (precos[item_compra] * quantidade)
  item_compra = int(input("Qual o identificador do item da compra? ")) 
  
  if (item_compra == -1):
    break
  itens_comprados.append(produtos[item_compra])

  informacao = input("Qual a quantidade consumida? ")
  while (not informacao.isdigit()):
    informacao = input("A quantidade consumida deve ser em um número. \nDigite novamente: ")
  quantidade = int(informacao)

print("*** Relatório final das compras ***")
for item in itens_comprados:
  print("Comprado: {}".format(item))
print("*******************************")
print("Total da compra {}".format(valor_total))