# -*- coding: utf-8 -*-
"""Desafio_Modulo4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nkZD4xNdp1Pk6yLx3YhInRKQl8QGcZgh
"""





# Notas Fiscais

#Funções
def inicializar_listas():
  clientes=["Marcelo","Joana D'arc","Maria de Fátima"]
  produtos=[{"nome":"computador","preco":1000.50},{"nome":"mouse","preco":120.10},{"nome":"Monitor LCD","preco":999.99}]
  
  return clientes, produtos

def ler_cliente(clientes):
  nome = input("Digite o nome do cliente (ou Enter para sair): ")

  while (nome != ""):
    for nome_lista in clientes:
      if (nome.upper() in nome_lista.upper()):
        return nome

    print("Não encontrei esse nome!")
    nome = input("Digite o nome do cliente (ou Enter para sair): ")

def ler_quantidade():
  informacao = input("Qual a quantidade? ")
  while (not informacao.isdigit()):
    informacao = input("A quantidade deve ser em um número. \nDigite novamente: ")
  
  return int(informacao)

def ler_produto(produtos):
  produto = input("Digite o nome do produto (ou Enter para sair): ")
  indice = -1
  
  if (produto == ""):
    return -1

  for i, item in enumerate(produtos):
    if (produto.upper() in item["nome"].upper()):
      indice = i
      break
  
  return indice

def processar_compra(produtos, itens_comprados):
  item_compra = ler_produto(produtos)
  if (item_compra == -1):
    return -1, 0

  itens_comprados.append(produtos[item_compra]["nome"])
  quantidade = ler_quantidade()
  return item_compra, quantidade

def preco_produdo(produtos, quantidade):
  preco_unidade = produtos[item_compra]["preco"]
  imposto_unidade = preco_unidade * 0.1

  return (preco_unidade * quantidade) + (imposto_unidade * quantidade)

#Programa principal
print("Aplicação sobre notas fiscais")
itens_comprados = []
valor_total = 0
clientes, produtos = inicializar_listas()

nome_cliente = ler_cliente(clientes)

if (nome_cliente):
  item_compra, quantidade = processar_compra(produtos, itens_comprados)

  while item_compra != -1:
    valor_total += preco_produdo(produtos, quantidade)
    item_compra, quantidade = processar_compra(produtos,itens_comprados)


print("*** Nota fiscal ***")
print("Cliente: {}".format(nome_cliente))

for item in itens_comprados:  
  print("{}".format(item))
print("*******************************")
print("Total da nota {}".format(valor_total))
print("Volte sempre!")

cliente = 'Joaquim José'

nome_buscado = "osé"

idade = 18

 

print((nome_buscado in cliente) and (not(idade < 18)))